name: quicknotes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:

  animated_text_kit: ^4.2.1
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firestore_search: ^0.1.3
  fl_chart: ^0.36.2
  flex_color_picker: ^2.0.1
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.0.5
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  keyboard_attachable: ^2.0.0
  modal_progress_hud: ^0.1.3
  path: ^1.8.0
  provider: ^5.0.0
  settings_ui: ^1.0.0
  sqflite: ^2.0.0
  waterfall_flow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
